package proyecto_final;

public enum Operacion {
    SUMAR, RESTAR, MULTIPLICAR, DIVIDIR,
    MODULO, POTENCIA, RAIZ_CUADRADA, VALOR_ABSOLUTO,
    SENO, COSENO, TANGENTE,
    LOGARITMO_NATURAL, LOGARITMO_COMUN,
    FACTORIAL, PORCENTAJE, TECHO, PISO, REDONDEAR
}